name: Build TrollStore Enhanced

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          build-essential \
          git \
          wget \
          curl \
          libtool \
          automake \
          autoconf \
          lzma \
          xz-utils \
          ldid \
          cmake
        
    - name: Setup Theos
      run: |
        # Clone Theos
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        
        # Install SDK
        curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip -q master.zip
        mkdir -p $GITHUB_WORKSPACE/theos/sdks
        mv sdks-master/*.sdk $GITHUB_WORKSPACE/theos/sdks/
        
        # Install toolchain
        curl -LO https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
        sudo mkdir -p /opt/ios-arm64e-clang-toolchain
        cd /opt
        sudo tar xf $GITHUB_WORKSPACE/linux-ios-arm64e-clang-toolchain.tar.lzma
        cd $GITHUB_WORKSPACE
        
        # Set environment variables
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/theos/bin:/opt/ios-arm64e-clang-toolchain/bin:$PATH" >> $GITHUB_ENV
        
    - name: Build TrollStore
      run: |
        export THEOS=$GITHUB_WORKSPACE/theos
        export PATH=$GITHUB_WORKSPACE/theos/bin:/opt/ios-arm64e-clang-toolchain/bin:$PATH
        make package FINALPACKAGE=1
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Build
        path: |
          packages/*.deb
          packages/*.ipa
        if-no-files-found: error
        
    - name: Create Release
      id: create_release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          TrollStore Enhanced Release
          
          New Features:
          - Enhanced exploit chain with CVE-2023-42824 and CVE-2023-41991
          - Real-time app modification system
          - Advanced logging and error handling
          - Environment variable control
        draft: false
        prerelease: false
        files: |
          packages/*.deb
          packages/*.ipa
