name: Build TrollStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    # Verify local tools
    - name: Verify Build Tools
      run: |
        chmod +x bins/build_tools.sh
        ./bins/build_tools.sh --verify
      
    # Setup build environment
    - name: Setup Environment
      run: |
        ./bins/build_tools.sh --setup
        
    # Build TrollStore
    - name: Build TrollStore
      run: |
        chmod +x bins/build_enhanced.sh
        ./bins/build_enhanced.sh
        
    # Run tests
    - name: Run Tests
      run: |
        chmod +x bins/debug_helper.sh
        ./bins/debug_helper.sh build/TrollStore.app/TrollStore
        
    # Create packages
    - name: Create Packages
      run: |
        cd packages
        mkdir -p Payload
        cp -r ../build/TrollStore.app Payload/
        zip -r TrollStore.ipa Payload
        rm -rf Payload
        
    # Upload artifacts
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: TrollStore
        path: packages/TrollStore.ipa
        
    - name: Upload Debug Logs
      uses: actions/upload-artifact@v2
      with:
        name: DebugLogs
        path: bins/debug/logs/
