name: Build TrollStore Enhanced

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang build-essential git wget fakeroot
        sudo apt-get install -y libtool automake autoconf
        sudo apt-get install -y libssl-dev zlib1g-dev
        sudo apt-get install -y cmake pkg-config
        
    - name: Install ldid
      uses: MOZGIII/install-ldid-action@v1
      with:
        tag: v2.1.5-procursus2
        
    - name: Setup theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        curl -LO https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
        sudo tar -xvf linux-ios-arm64e-clang-toolchain.tar.lzma -C /opt
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "THEOS_MAKE_PATH=$GITHUB_WORKSPACE/theos/makefiles" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/theos/bin:/opt/ios-arm64e-clang-toolchain/bin:$PATH" >> $GITHUB_ENV
        
    - name: Install iOS SDK
      run: |
        mkdir -p $GITHUB_WORKSPACE/theos/sdks
        cd $GITHUB_WORKSPACE/theos/sdks
        wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
        unzip -q sdks.zip
        mv sdks-master/*.sdk ./
        rm -rf sdks-master sdks.zip
        ls -la
        
    - name: Prepare Build Environment
      run: |
        mkdir -p packages
        chmod +x $GITHUB_WORKSPACE/theos/bin/*
        make clean || true
        
    - name: Setup SDK Symlinks
      run: |
        sudo mkdir -p /opt/ios-arm64e-clang-toolchain/SDK
        sudo ln -sf $GITHUB_WORKSPACE/theos/sdks/iPhoneOS16.2.sdk /opt/ios-arm64e-clang-toolchain/SDK/iPhoneOS16.2.sdk
        
    - name: Build TrollStore
      run: |
        export THEOS_PLATFORM_SDK_ROOT=/opt/ios-arm64e-clang-toolchain/SDK
        export SDKVERSION=16.2
        export SYSROOT=/opt/ios-arm64e-clang-toolchain/SDK/iPhoneOS16.2.sdk
        export THEOS_PLATFORM_SDK_ROOT_arm64=/opt/ios-arm64e-clang-toolchain/SDK
        export THEOS_PLATFORM_SDK_ROOT_arm64e=/opt/ios-arm64e-clang-toolchain/SDK
        export PATH=/opt/ios-arm64e-clang-toolchain/bin:$PATH
        
        # Debug information
        echo "Current directory: $(pwd)"
        echo "THEOS: $THEOS"
        echo "SDK Path: $SYSROOT"
        ls -la $GITHUB_WORKSPACE/theos/sdks/
        
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Build
        path: |
          packages/*.deb
          packages/*.ipa
        if-no-files-found: error
        
    - name: Create Release
      id: create_release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          TrollStore Enhanced Release
          
          New Features:
          - Enhanced exploit chain with CVE-2023-42824 and CVE-2023-41991
          - Real-time app modification system
          - Advanced logging and error handling
          - Environment variable control
          - iOS 17 compatibility improvements
        draft: false
        prerelease: false
        files: |
          packages/*.deb
          packages/*.ipa
