name: Build TrollStore Enhanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          build-essential \
          git \
          wget \
          libtool \
          automake \
          autoconf \
          lzma \
          xz-utils
        
    - name: Setup Theos
      run: |
        # Clone Theos
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        
        # Download and install iOS SDK
        wget https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mkdir -p $GITHUB_WORKSPACE/theos/sdks
        mv sdks-master/*.sdk $GITHUB_WORKSPACE/theos/sdks/
        
        # Download and install LLVM toolchain
        wget https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
        sudo mkdir -p /opt/ios-arm64e-clang-toolchain
        sudo tar -xvf linux-ios-arm64e-clang-toolchain.tar.lzma -C /opt
        
        # Set environment variables
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/theos/bin:/opt/ios-arm64e-clang-toolchain/bin:$PATH" >> $GITHUB_ENV
        
    - name: Build TrollStore
      run: |
        make package FINALPACKAGE=1
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          TrollStore Enhanced Release
          
          New Features:
          - Enhanced exploit chain with CVE-2023-42824 and CVE-2023-41991
          - Real-time app modification system
          - Advanced logging and error handling
          - Environment variable control
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./packages/com.opa334.trollstore_2.0_iphoneos-arm.deb
        asset_name: TrollStore-Enhanced.deb
        asset_content_type: application/vnd.debian.binary-package
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TrollStore-Build
        path: |
          ./packages/*.deb
          ./packages/*.ipa
