name: Build TrollStore Enhanced

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang build-essential git wget
        sudo apt-get install -y libtool automake autoconf
        
    - name: Install ldid
      uses: MOZGIII/install-ldid-action@v1
      with:
        tag: v2.1.5-procursus2
        
    - name: Setup theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        curl -LO https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
        sudo tar -xvf linux-ios-arm64e-clang-toolchain.tar.lzma -C /opt
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/theos/bin:/opt/ios-arm64e-clang-toolchain/bin:$PATH" >> $GITHUB_ENV
        
    - name: Install iOS SDK
      run: |
        wget https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        sudo mv sdks-master/*.sdk $GITHUB_WORKSPACE/theos/sdks/
        
    - name: Build TrollStore
      run: |
        make package FINALPACKAGE=1
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Build
        path: |
          packages/*.deb
          packages/*.ipa
        if-no-files-found: error
        
    - name: Create Release
      id: create_release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          TrollStore Enhanced Release
          
          New Features:
          - Enhanced exploit chain with CVE-2023-42824 and CVE-2023-41991
          - Real-time app modification system
          - Advanced logging and error handling
          - Environment variable control
        draft: false
        prerelease: false
        files: |
          packages/*.deb
          packages/*.ipa
